Cel zadania

Opracowac strategie najlepszego kupowania akcji pewnej firmy na podstawy wiedzy historycznej.


etap - jeden dzien na gieldzie
decyzja - ile akcji kupimy (mozemy kupowac tylko calkowite akcje)
stan - ile akcji jest aktualnie kupionych

funkcja celu

- 2 <= x <= 2
x >= -y
aktualny kapital // cena akcji >= x


maksymalizujemy zysk
2. max y * cena akcji + aktualny kapital - poczatkowy kapital



ogranicznia:
- maksymalna liczba akcji ktore mozna kupic ()
- minimalna liczba akcji ktore mozna kupic
- maksymalna akcji ktore mozna posiadac
- aktualny kapital

In [11]:
import numpy as np

In [75]:
def max_profit(kapital_pocz, hist, max_akcji, max_buy_sell):
    days = len(hist) - 1
    result = [0 for _ in range(days)]
    table = np.zeros((max_akcji+1, 2*days+1))
    f_col = 2
    x_col = 1
    etap = days - 1

    current = kapital_pocz

    while f_col < 2*days + 1:
        for y in range(max_akcji+1):
            maximum = -np.inf
            akcje = 0
            for x in range(max(-max_buy_sell, -int(y)), min(current//hist[etap], max_buy_sell, max_akcji-y)+1):
                if x+y >= 0 and x+y < max_akcji+1:
                    value = hist[etap+1]*(y+x) - hist[etap] * y + table[y+x][f_col]
                else:
                    value = hist[etap+1]*(y+x) - hist[etap] * y

                if value > maximum:
                    akcje = x
                    maximum = value
            
            current += akcje*hist[etap]
            table[y][f_col] = maximum
            table[y][x_col] = akcje
        f_col += 2
        x_col += 2
        etap -= 1
    return table

print("Tablica wyliczonych wartosci: \n", max_profit(500, [50, 100, 70, 40], 4, 2))

Tablica wyliczonych wartosci: 
 [[   0.    2.   80.    2.  140.    2.  200.]
 [   0.    2.   50.    2.  110.    2.  250.]
 [   0.    2.   20.    2.   80.    2.  300.]
 [   0.    1.  -50.    1.  -20.   -1.  350.]
 [   0.    0. -120.    0. -120.   -1.  450.]]
