In [1]:
import numpy as np

In [2]:
def OPR(cost_production, cost_storage, req_products, number_of_months, min_storage, max_storage, ending_storage):
    mat_choose = np.zeros((max_storage - min_storage + 1, number_of_months))
    mat_profit = np.zeros((max_storage - min_storage + 1, number_of_months))

    ## Inicjalizacja 1 kolumny
    for i in range(mat_choose.shape[0]):
        choose = ending_con + req_products[-1] - (i + min_storage)
        if choose >= 0:
            mat_choose[i,0] = choose
            mat_profit[i,0] = cost_production[choose]
        else:
            mat_choose[i,0] = np.inf
            mat_profit[i,0] = np.inf

    # print(mat_profit)
    for i in range(1,mat_choose.shape[1]):## kolumny
        for j in range(mat_choose.shape[0]): ## wiersze
            val = 255
            pos = 0
            for k in range(len(cost_production) + 1):
                if (k > min_storage + req[-i-1] - (j + min_storage)) and (k < max_storage + req[-i-1] - (j + min_storage)) and (k < max_storage):
                    val_help = cost_production[k] + cost_storage[k + j - req[-i-1]] + mat_profit[k+j-req[-i-1] - 1,i-1]
                    # print(f"({i},{j}),  {k}: {val_help}")
                    if val_help < val:
                        val = val_help
                        pos = k
            if pos >= 0 and val != 255:
                mat_choose[j,i] = pos
                mat_profit[j,i] = val
            else:
                mat_choose[j,i] = np.inf
                mat_profit[j,i] = np.inf


    return mat_choose, mat_profit

In [3]:
def find_optimal_solution(mat_choose, mat_profit, req_products, start, min_storage):
    optimal_solution = []
    
    value_to_choose = mat_choose[start - min_storage,-1] ## wartosc produkcji 
    optimal_solution.append(value_to_choose)
    storage = start + value_to_choose - req_products[0] ## ile ma przejsc do magazynu 
    for i in range(1,mat_choose.shape[1]):
        # print(value_to_choose)
        if value_to_choose == np.inf:
            return ['Impossible']
        # print(value_to_choose)
        value_to_choose = mat_choose[int(storage) - min_storage,-i-1]
        optimal_solution.append(value_to_choose)
        storage += value_to_choose - req_products[i]
        
    return optimal_solution


In [4]:
## koszt produckji
cost = [0,5,7,8,15,20,15,14]

## koszt skladowania
cost_storage = [0,5,9,10,11,12,13,14,13]

## Zapotrzebowanie
req = [3,1,1,4,3,3,5,7,5,5,4,3,1]

min_storage = 1
max_storage = len(cost_storage) - 1

starting_con = 4
ending_con = 7
number_of_months = 12


In [5]:
mat_c, mat_p = OPR(cost,cost_storage,req,number_of_months,min_storage,max_storage,ending_con)
print(mat_c)
print(mat_p)

[[ 7.  4.  7.  6.  6. inf  7.  4.  7.  7.  2.  2.]
 [ 6.  3.  7.  7.  6.  7.  6.  3.  7.  7.  1.  1.]
 [ 5.  2.  7.  7.  7.  6.  6.  2.  3.  3.  0.  0.]
 [ 4.  1.  3.  3.  3.  7.  4.  1.  2.  2.  0.  0.]
 [ 3.  0.  2.  2.  2.  7.  3.  0.  0.  1.  0.  0.]
 [ 2.  0.  0.  1.  1.  3.  2.  0.  0.  0.  0.  0.]
 [ 1.  2.  0.  0.  0.  2.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  1.  0.  1.  0.  0.  0.  0.]]
[[ 14.  34.  50.  70.  90.  inf 132. 152. 167. 186. 198. 210.]
 [ 15.  27.  49.  69.  93. 109. 133. 145. 163. 186. 196. 208.]
 [ 20.  26.  45.  69.  88. 110. 135. 144. 162. 180. 191. 203.]
 [ 15.  24.  44.  63.  83. 112. 133. 142. 161. 179. 195. 205.]
 [  8.  19.  43.  62.  82. 108. 126. 137. 157. 177. 190. 201.]
 [  7.  24.  39.  60.  80. 103. 125. 142. 154. 172. 190. 206.]
 [  5.  27.  36.  55.  75. 102. 123. 145. 154. 172. 189. 202.]
 [  0.  25.  36.  58.  78. 100. 118. 143. 153. 172. 185. 203.]]


In [262]:
opt_choose = find_optimal_solution(mat_c,mat_p,req,starting_con, min_storage)
print(opt_choose)

[0.0, 2.0, 7.0, 0.0, 1.0, 6.0, 7.0, 0.0, 0.0, 7.0, 0.0, 7.0]
